import type { DatabaseProperty, DatabaseRow, Json } from '../../types/database.types'
import { getCellValue, propertyConfig } from '../../utils/database'

export function DatabaseBoard({ rows, properties, canWrite, onCommit, onOpenRow, onCreateRow }: { rows: DatabaseRow[]; properties: DatabaseProperty[]; canWrite: boolean; onCommit: (row: DatabaseRow, propertyId: string, value: Json | undefined) => void; onOpenRow: (row: DatabaseRow) => void; onCreateRow: () => void }) {
  const title = properties.find((property) => property.property_type === 'title')
  const group = properties.find((property) => property.property_type === 'select')
  if (!group || !title) return <div className="p-8 text-sm text-neutral-500">Board view needs at least one Select property. Add a Select property such as Status.</div>
  const options = propertyConfig(group).options ?? []
  const columns = [{ id: '__empty__', label: 'No status' }, ...options]
  return <div className="flex min-h-full gap-3 overflow-x-auto bg-neutral-50/50 p-4">{columns.map((option) => { const items = rows.filter((row) => option.id === '__empty__' ? !getCellValue(row, group.id) : getCellValue(row, group.id) === option.id); return <section key={option.id} className="w-72 shrink-0"><div className="mb-2 flex items-center justify-between px-1 text-xs font-semibold text-neutral-600"><span>{option.label}</span><span className="rounded bg-neutral-200 px-1.5 py-0.5 text-[10px] text-neutral-500">{items.length}</span></div><div className="space-y-2">{items.map((row) => <article key={row.id} onClick={() => onOpenRow(row)} className="cursor-pointer rounded-lg border border-neutral-200 bg-white p-3 shadow-sm hover:border-neutral-300"><div className="text-sm font-medium text-neutral-800">{String(getCellValue(row, title.id) ?? 'Untitled')}</div>{canWrite ? <select onClick={(event) => event.stopPropagation()} value={String(getCellValue(row, group.id) ?? '')} onChange={(event) => onCommit(row, group.id, event.target.value || undefined)} className="mt-3 h-7 w-full rounded border border-neutral-100 bg-neutral-50 px-2 text-[11px] text-neutral-500"><option value="">No status</option>{options.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select> : null}</article>)}{canWrite ? <button onClick={onCreateRow} className="w-full rounded-md px-2 py-2 text-left text-xs text-neutral-400 hover:bg-white hover:text-neutral-700">+ New</button> : null}</div></section> })}</div>
}
