import { useMemo, useState } from 'react'
import { ChevronLeft, ChevronRight } from 'lucide-react'
import type { DatabaseProperty, DatabaseRow } from '../../types/database.types'
import { getCellValue } from '../../utils/database'

function ymd(date: Date) { return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}` }

export function DatabaseCalendar({ rows, properties, onOpenRow }: { rows: DatabaseRow[]; properties: DatabaseProperty[]; onOpenRow: (row: DatabaseRow) => void }) {
  const [month, setMonth] = useState(() => { const date = new Date(); return new Date(date.getFullYear(), date.getMonth(), 1) })
  const dateProperty = properties.find((property) => property.property_type === 'date' || property.property_type === 'datetime')
  const title = properties.find((property) => property.property_type === 'title')
  const cells = useMemo(() => { const firstDay = month.getDay(); const days = new Date(month.getFullYear(), month.getMonth() + 1, 0).getDate(); const result: Array<Date | null> = Array(firstDay).fill(null); for (let day = 1; day <= days; day += 1) result.push(new Date(month.getFullYear(), month.getMonth(), day)); while (result.length % 7) result.push(null); return result }, [month])
  if (!dateProperty) return <div className="p-8 text-sm text-neutral-500">Calendar view needs a Date or Date & time property.</div>
  return <div className="p-4"><div className="mb-3 flex items-center gap-2"><button onClick={() => setMonth(new Date(month.getFullYear(), month.getMonth() - 1, 1))} className="rounded p-1.5 hover:bg-neutral-100"><ChevronLeft size={16} /></button><button onClick={() => setMonth(new Date())} className="rounded px-2 py-1 text-xs hover:bg-neutral-100">Today</button><button onClick={() => setMonth(new Date(month.getFullYear(), month.getMonth() + 1, 1))} className="rounded p-1.5 hover:bg-neutral-100"><ChevronRight size={16} /></button><h2 className="ml-2 text-sm font-semibold">{month.toLocaleDateString(undefined, { month: 'long', year: 'numeric' })}</h2></div><div className="grid grid-cols-7 border-l border-t border-neutral-200">{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map((day) => <div key={day} className="border-b border-r border-neutral-200 bg-neutral-50 px-2 py-2 text-[10px] font-semibold uppercase tracking-wide text-neutral-400">{day}</div>)}{cells.map((date, index) => { const key = date ? ymd(date) : `empty-${index}`; const items = date ? rows.filter((row) => String(getCellValue(row, dateProperty.id) ?? '').slice(0, 10) === key) : []; return <div key={key} className="min-h-28 border-b border-r border-neutral-200 p-1.5"><div className="mb-1 text-[11px] text-neutral-400">{date?.getDate() ?? ''}</div><div className="space-y-1">{items.slice(0, 4).map((row) => <button key={row.id} onClick={() => onOpenRow(row)} className="block w-full truncate rounded bg-neutral-100 px-1.5 py-1 text-left text-[10px] hover:bg-neutral-200">{title ? String(getCellValue(row, title.id) ?? 'Untitled') : 'Untitled'}</button>)}{items.length > 4 ? <div className="px-1 text-[10px] text-neutral-400">+{items.length - 4} more</div> : null}</div></div> })}</div></div>
}
