import { useMemo, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { MoreHorizontal, Plus, Search } from 'lucide-react'
import { useWorkspaceOutlet } from '../features/workspace/useWorkspaceOutlet'
import { useWorkspaceMembers, useWorkspacePermissions, workspaceKeys } from '../features/workspace/queries'
import { cancelInvite, listPendingInvites, resendInvite } from '../services/member.service'
import { changeMemberRole, removeWorkspaceMember } from '../services/workspace.service'
import { canInvite, canManageRoles } from '../utils/permissions'
import type { EditableRole } from '../types/domain'
import { Avatar } from '../components/ui/Avatar'
import { Button } from '../components/ui/Button'
import { Input } from '../components/ui/Input'
import { Modal } from '../components/ui/Modal'
import { InviteMemberModal } from '../components/members/InviteMemberModal'
import { formatDate } from '../utils/format'
import { useToast } from '../components/ui/Toast'

export function MembersPage() {
  const { workspace, role } = useWorkspaceOutlet()
  const members = useWorkspaceMembers(workspace.id)
  const permissions = useWorkspacePermissions(workspace.id)
  const mayInvite = canInvite(role, permissions.data)
  const invites = useQuery({ queryKey: ['workspace', workspace.id, 'invites'], queryFn: () => listPendingInvites(workspace.id), enabled: mayInvite })
  const [inviteOpen, setInviteOpen] = useState(false)
  const [menu, setMenu] = useState<string | null>(null)
  const [confirm, setConfirm] = useState<{ kind: 'member' | 'invite'; id: string; label: string } | null>(null)
  const [tab, setTab] = useState<'all' | 'pending' | 'admins'>('all')
  const [search, setSearch] = useState('')
  const queryClient = useQueryClient()
  const { push } = useToast()
  const refresh = async () => { await Promise.all([queryClient.invalidateQueries({ queryKey: workspaceKeys.members(workspace.id) }), queryClient.invalidateQueries({ queryKey: ['workspace', workspace.id, 'invites'] })]) }
  const changeRole = useMutation({ mutationFn: ({ memberId, nextRole }: { memberId: string; nextRole: EditableRole }) => changeMemberRole(workspace.id, memberId, nextRole), onSuccess: async () => { await refresh(); push('Role updated.', 'success') }, onError: () => push('Could not update the role.', 'error') })
  const remove = useMutation({ mutationFn: (memberId: string) => removeWorkspaceMember(workspace.id, memberId), onSuccess: async () => { await refresh(); setConfirm(null); push('Member removed.', 'success') }, onError: () => push('Could not remove this member.', 'error') })
  const cancel = useMutation({ mutationFn: (inviteId: string) => cancelInvite(workspace.id, inviteId), onSuccess: async () => { await refresh(); setConfirm(null); push('Invitation cancelled.', 'success') }, onError: () => push('Could not cancel the invitation.', 'error') })
  const resend = useMutation({ mutationFn: (inviteId: string) => resendInvite(workspace.id, inviteId), onSuccess: async () => { await refresh(); push('Invitation resent.', 'success') }, onError: (error) => push(error instanceof Error ? error.message : 'Could not resend the invitation.', 'error') })
  const filteredMembers = useMemo(() => (members.data ?? []).filter((member) => (tab !== 'admins' || member.role === 'OWNER' || member.role === 'ADMIN') && `${member.profile?.full_name ?? ''} ${member.profile?.email ?? ''}`.toLowerCase().includes(search.toLowerCase())), [members.data, tab, search])
  const filteredInvites = useMemo(() => (invites.data ?? []).filter((invite) => invite.email.toLowerCase().includes(search.toLowerCase())), [invites.data, search])
  const showingMembers = tab !== 'pending'
  const showingInvites = mayInvite && tab !== 'admins'

  return <div className="mx-auto max-w-5xl px-4 py-8 sm:px-6 md:py-10"><header className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><h1 className="text-2xl font-semibold tracking-tight">Members</h1><p className="mt-1 text-sm text-neutral-500">Manage who can access this workspace.</p></div>{mayInvite ? <Button variant="primary" onClick={() => setInviteOpen(true)}><Plus size={15} /> Invite member</Button> : null}</header>
    <div className="mt-8 flex flex-wrap items-center justify-between gap-3 border-b border-neutral-200"><div className="flex gap-5">{(['all', 'pending', 'admins'] as const).filter((item) => item !== 'pending' || mayInvite).map((item) => <button key={item} onClick={() => setTab(item)} className={`border-b-2 pb-3 text-sm capitalize transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-neutral-700 ${tab === item ? 'border-neutral-900 font-medium text-neutral-900' : 'border-transparent text-neutral-500 hover:text-neutral-800'}`}>{item === 'all' ? `All ${members.data?.length ?? ''}` : item === 'pending' ? `Pending ${invites.data?.length ?? ''}` : 'Admins'}</button>)}</div><div className="relative mb-2 w-full sm:w-56"><Search size={15} className="pointer-events-none absolute left-2.5 top-1/2 -translate-y-1/2 text-neutral-400" /><Input aria-label="Search members" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search members" className="h-8 pl-8" /></div></div>
    {(members.isPending || (showingInvites && invites.isPending)) ? <div className="mt-5 h-28 animate-pulse rounded-xl bg-neutral-100" role="status" aria-label="Loading members" /> : (members.isError || (showingInvites && invites.isError)) ? <div className="mt-5 rounded-xl border border-neutral-200 p-5 text-sm text-neutral-600">Could not load members. <Button size="sm" onClick={() => { void members.refetch(); void invites.refetch() }}>Try again</Button></div> : <>
      {showingMembers && filteredMembers.length ? <div className="mt-5 divide-y divide-neutral-100 rounded-xl border border-neutral-200">{filteredMembers.map((member) => <div key={member.id} className="flex min-w-0 items-center gap-3 px-3 py-3 sm:px-4"><Avatar name={member.profile?.full_name} email={member.profile?.email} url={member.profile?.avatar_url} /><div className="min-w-0 flex-1"><div className="truncate text-sm font-medium text-neutral-900" title={member.profile?.full_name ?? undefined}>{member.profile?.full_name || member.profile?.email || 'Workspace member'}</div><div className="truncate text-xs text-neutral-500" title={member.profile?.email ?? undefined}>{member.profile?.email}</div></div><div className="hidden text-xs text-neutral-500 sm:block">Joined {formatDate(member.joined_at)}</div><span className="rounded-md bg-neutral-100 px-2 py-1 text-[11px] font-medium capitalize text-neutral-700">{member.role.toLowerCase()}</span>{canManageRoles(role) && member.role !== 'OWNER' ? <div className="relative"><button aria-label={`Actions for ${member.profile?.full_name || member.profile?.email || 'member'}`} aria-expanded={menu === member.id} onClick={() => setMenu(menu === member.id ? null : member.id)} className="rounded-md p-2 text-neutral-500 hover:bg-neutral-100 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-neutral-700"><MoreHorizontal size={17} /></button>{menu === member.id ? <div className="absolute right-0 top-9 z-20 w-44 rounded-lg border border-neutral-200 bg-white p-1 shadow-panel"><div className="px-2 py-1 text-[11px] text-neutral-500">Workspace role</div>{(['ADMIN','MEMBER','VIEWER'] as const).map((nextRole) => <button key={nextRole} disabled={member.role === nextRole || changeRole.isPending} onClick={() => { changeRole.mutate({ memberId: member.id, nextRole }); setMenu(null) }} className="block w-full rounded px-2 py-2 text-left text-xs hover:bg-neutral-50 disabled:text-neutral-400">{nextRole[0]}{nextRole.slice(1).toLowerCase()}</button>)}<button onClick={() => { setMenu(null); setConfirm({ kind: 'member', id: member.id, label: member.profile?.full_name || member.profile?.email || 'this member' }) }} className="mt-1 block w-full border-t border-neutral-100 px-2 py-2 text-left text-xs text-red-600 hover:bg-red-50">Remove member</button></div> : null}</div> : null}</div>)}</div> : null}
      {showingInvites && filteredInvites.length ? <section className="mt-8"><h2 className="mb-3 text-sm font-semibold">Pending invitations</h2><div className="divide-y divide-neutral-100 rounded-xl border border-neutral-200">{filteredInvites.map((invite) => <div key={invite.id} className="flex flex-wrap items-center gap-2 px-4 py-3 sm:gap-3"><div className="min-w-0 flex-1"><div className="truncate text-sm font-medium">{invite.email}</div><div className="text-xs text-neutral-500">{invite.role.toLowerCase()} · Expires {formatDate(invite.expires_at)}</div></div><Button size="sm" onClick={() => resend.mutate(invite.id)} disabled={resend.isPending}>Resend</Button><Button size="sm" variant="ghost" onClick={() => setConfirm({ kind: 'invite', id: invite.id, label: invite.email })}>Cancel</Button></div>)}</div></section> : null}
      {((tab === 'pending' && !filteredInvites.length) || (tab === 'admins' && !filteredMembers.length) || (tab === 'all' && !filteredMembers.length && !filteredInvites.length)) ? <div className="mt-5 rounded-xl border border-neutral-200 bg-neutral-50 px-5 py-10 text-center"><h2 className="text-sm font-semibold">{search ? 'No matches' : tab === 'pending' ? 'No pending invitations' : 'No other members yet'}</h2><p className="mt-1 text-sm text-neutral-500">{search ? 'Try another search.' : 'Invite your team to start collaborating.'}</p>{mayInvite && !search && tab === 'all' ? <Button className="mt-4" onClick={() => setInviteOpen(true)}>Invite member</Button> : null}</div> : null}
    </>}
    <InviteMemberModal open={inviteOpen} workspaceId={workspace.id} onClose={() => setInviteOpen(false)} onInvited={() => void refresh()} />
    <Modal open={Boolean(confirm)} onClose={() => setConfirm(null)} title={confirm?.kind === 'member' ? 'Remove member' : 'Cancel invitation'}><p className="text-sm text-neutral-600">{confirm?.kind === 'member' ? `Remove ${confirm.label} from this workspace? They will lose access to its teams and content.` : `Cancel the invitation for ${confirm?.label}? The invitation link will stop working.`}</p><div className="mt-6 flex justify-end gap-2"><Button onClick={() => setConfirm(null)}>Keep</Button><Button variant="danger" disabled={remove.isPending || cancel.isPending} onClick={() => { if (!confirm) return; if (confirm.kind === 'member') remove.mutate(confirm.id); else cancel.mutate(confirm.id) }}>{confirm?.kind === 'member' ? 'Remove member' : 'Cancel invitation'}</Button></div></Modal>
  </div>
}
