import { useEffect, useState } from 'react'
import { Link, useNavigate, useSearchParams } from 'react-router-dom'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { useWorkspaceOutlet } from '../features/workspace/useWorkspaceOutlet'
import { useWorkspaceMembers, useWorkspacePermissions, workspaceKeys } from '../features/workspace/queries'
import { useTeams } from '../features/teams/queries'
import { deleteWorkspace, leaveWorkspace, updateWorkspaceSettings } from '../services/workspace.service'
import { listPendingInvites } from '../services/member.service'
import { updateWorkspacePermissions } from '../services/settings.service'
import { canInvite } from '../utils/permissions'
import { devBypassEnabled } from '../lib/dev-bypass'
import type { WorkspaceSettings } from '../types/database.types'
import { Button } from '../components/ui/Button'
import { Input } from '../components/ui/Input'
import { Modal } from '../components/ui/Modal'
import { useToast } from '../components/ui/Toast'

const sections = ['general', 'people', 'permissions', 'teams', 'security', 'danger'] as const
type Section = typeof sections[number]
const permissionFields = [
  ['who_can_invite', 'Invite members'],
  ['who_can_create_team', 'Create teams'],
  ['who_can_create_collection', 'Create collections'],
  ['who_can_create_page', 'Create pages'],
] as const

export function WorkspaceSettingsPage() {
  const { workspace, role } = useWorkspaceOutlet()
  const [params, setParams] = useSearchParams()
  const section = sections.includes(params.get('section') as Section) ? params.get('section') as Section : 'general'
  const [name, setName] = useState(workspace.name)
  const [logoUrl, setLogoUrl] = useState(workspace.logo_url ?? '')
  const [permissionDraft, setPermissionDraft] = useState<WorkspaceSettings | null>(null)
  const [confirm, setConfirm] = useState<'leave' | 'delete' | null>(null)
  const [deleteName, setDeleteName] = useState('')
  const permissions = useWorkspacePermissions(workspace.id)
  const people = useWorkspaceMembers(section === 'people' ? workspace.id : undefined)
  const teams = useTeams(section === 'teams' ? workspace.id : undefined)
  const invites = useQuery({ queryKey: ['workspace', workspace.id, 'invites'], queryFn: () => listPendingInvites(workspace.id), enabled: (section === 'people' || section === 'security') && canInvite(role, permissions.data) })
  const queryClient = useQueryClient()
  const navigate = useNavigate()
  const { push } = useToast()
  const editable = role === 'OWNER' || role === 'ADMIN'
  useEffect(() => { setName(workspace.name); setLogoUrl(workspace.logo_url ?? '') }, [workspace.id, workspace.name, workspace.logo_url])
  useEffect(() => { setPermissionDraft(permissions.data ?? null) }, [permissions.data])
  const saveGeneral = useMutation({ mutationFn: () => updateWorkspaceSettings(workspace.id, { name: name.trim(), logo_url: logoUrl.trim() || null }), onSuccess: async () => { await Promise.all([queryClient.invalidateQueries({ queryKey: workspaceKeys.bySlug(workspace.slug) }), queryClient.invalidateQueries({ queryKey: workspaceKeys.all })]); push('Workspace settings saved.', 'success') }, onError: () => push('Could not save workspace settings.', 'error') })
  const savePermissions = useMutation({ mutationFn: () => updateWorkspacePermissions(workspace.id, permissionDraft ?? {}), onSuccess: async () => { await queryClient.invalidateQueries({ queryKey: workspaceKeys.settings(workspace.id) }); push('Permissions saved.', 'success') }, onError: () => push('Could not save permissions.', 'error') })
  const danger = useMutation({ mutationFn: () => confirm === 'delete' ? deleteWorkspace(workspace.id, deleteName) : leaveWorkspace(workspace.id), onSuccess: async () => { await queryClient.invalidateQueries({ queryKey: workspaceKeys.all }); setConfirm(null); navigate('/app', { replace: true }) }, onError: (error) => push(error instanceof Error ? error.message : 'Action failed.', 'error') })
  const activeNav = (item: Section) => `w-full rounded-lg px-3 py-2 text-left text-sm transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-neutral-700 ${section === item ? 'bg-neutral-100 font-medium text-neutral-900' : 'text-neutral-600 hover:bg-neutral-50 hover:text-neutral-900'}`

  return <div className="mx-auto max-w-5xl px-4 py-8 sm:px-6 md:py-10"><h1 className="text-2xl font-semibold tracking-tight">Settings</h1><p className="mt-1 text-sm text-neutral-500">Manage this workspace and how people work together.</p><div className="mt-8 grid gap-8 md:grid-cols-[190px_minmax(0,1fr)]">
    <nav aria-label="Settings sections" className="flex gap-1 overflow-x-auto pb-2 md:flex-col md:overflow-visible">{sections.map((item) => <button key={item} onClick={() => setParams({ section: item })} className={`${activeNav(item)} whitespace-nowrap md:whitespace-normal`}>{item === 'danger' ? 'Danger zone' : item.charAt(0).toUpperCase() + item.slice(1)}</button>)}</nav>
    <div className="min-w-0">
      {section === 'general' ? <section><h2 className="text-base font-semibold">General</h2><p className="mt-1 text-sm text-neutral-500">Name and identity for this workspace.</p><div className="mt-6 flex items-center gap-4"><div className="grid h-14 w-14 place-items-center overflow-hidden rounded-xl bg-neutral-100 text-lg font-bold text-neutral-600">{logoUrl ? <img src={logoUrl} alt="" className="h-full w-full object-cover" /> : workspace.name[0]?.toUpperCase()}</div><span className="text-xs text-neutral-500">Workspace icon preview</span></div><div className="mt-6 max-w-lg space-y-4"><label className="block text-sm font-medium">Workspace name<Input className="mt-1" maxLength={120} disabled={!editable} value={name} onChange={(event) => setName(event.target.value)} /></label><label className="block text-sm font-medium">Icon URL<Input className="mt-1" disabled={!editable} value={logoUrl} onChange={(event) => setLogoUrl(event.target.value)} placeholder="https://…" /></label><div><div className="text-sm font-medium">Workspace address</div><div className="mt-1 rounded-lg border border-neutral-200 bg-neutral-50 px-3 py-2 text-sm text-neutral-600">/app/{workspace.slug}</div></div>{editable ? <Button variant="primary" onClick={() => saveGeneral.mutate()} disabled={!name.trim() || saveGeneral.isPending}>{saveGeneral.isPending ? 'Saving…' : 'Save changes'}</Button> : <p className="text-sm text-neutral-500">Owners and admins can edit these settings.</p>}</div></section> : null}
      {section === 'people' ? <section><h2 className="text-base font-semibold">People</h2><p className="mt-1 text-sm text-neutral-500">Workspace access is managed in Members.</p><div className="mt-6 grid gap-3 sm:grid-cols-3">{[['Members', people.data?.length, people.isPending], ['Pending invitations', invites.data?.length, invites.isPending], ['Admins', people.data?.filter((item) => item.role === 'ADMIN' || item.role === 'OWNER').length, people.isPending]] .map(([label, count, loading]) => <div key={String(label)} className="rounded-xl border border-neutral-200 p-4"><div className="text-xs text-neutral-500">{label}</div><div className="mt-2 text-xl font-semibold">{loading ? '…' : count ?? '—'}</div></div>)}</div><Link to={`/app/${workspace.slug}/settings/members`} className="mt-5 inline-flex h-9 items-center rounded-lg border border-neutral-200 px-3 text-sm font-medium hover:bg-neutral-50">Manage members</Link></section> : null}
      {section === 'permissions' ? <section><h2 className="text-base font-semibold">Permissions</h2><p className="mt-1 text-sm text-neutral-500">Choose who can create and invite. Owners and admins can always do these actions.</p>{permissions.isPending ? <div className="mt-6 h-32 animate-pulse rounded-xl bg-neutral-100" /> : permissions.isError ? <p className="mt-6 text-sm text-red-600">Could not load permissions.</p> : permissionDraft ? <div className="mt-6 max-w-lg space-y-0 divide-y divide-neutral-100 rounded-xl border border-neutral-200 px-4">{permissionFields.map(([key, label]) => <label key={key} className="flex flex-wrap items-center justify-between gap-3 py-4 text-sm"><span className="font-medium">{label}</span><select value={permissionDraft[key]} disabled={!editable} onChange={(event) => setPermissionDraft({ ...permissionDraft, [key]: event.target.value as 'admins' | 'everyone' })} className="h-9 rounded-lg border border-neutral-200 bg-white px-3 text-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-neutral-700"><option value="admins">Owners and admins</option><option value="everyone">All members</option></select></label>)}</div> : null}{editable && permissionDraft ? <Button className="mt-5" variant="primary" disabled={savePermissions.isPending} onClick={() => savePermissions.mutate()}>{savePermissions.isPending ? 'Saving…' : 'Save permissions'}</Button> : null}</section> : null}
      {section === 'teams' ? <section><h2 className="text-base font-semibold">Teams</h2><p className="mt-1 text-sm text-neutral-500">Group existing workspace members.</p>{teams.isPending ? <div className="mt-6 h-20 animate-pulse rounded-xl bg-neutral-100" /> : teams.isError ? <p className="mt-6 text-sm text-red-600">Could not load teams.</p> : <div className="mt-6 divide-y divide-neutral-100 rounded-xl border border-neutral-200">{teams.data?.length ? teams.data.map((team) => <Link key={team.id} to={`/app/${workspace.slug}/teams/${team.id}`} className="flex items-center gap-3 px-4 py-3 text-sm hover:bg-neutral-50"><span aria-hidden="true">{team.icon || '◌'}</span><span className="font-medium">{team.name}</span></Link>) : <p className="p-5 text-sm text-neutral-500">No teams yet.</p>}</div>}<Link to={`/app/${workspace.slug}/teams`} className="mt-5 inline-flex h-9 items-center rounded-lg border border-neutral-200 px-3 text-sm font-medium hover:bg-neutral-50">Manage teams</Link></section> : null}
      {section === 'security' ? <section><h2 className="text-base font-semibold">Security</h2><p className="mt-1 text-sm text-neutral-500">Invitations expire after seven days. Pending links can be cancelled in Members.</p>{canInvite(role, permissions.data) ? <div className="mt-6 rounded-xl border border-neutral-200 p-5"><div className="text-sm font-medium">Active invitations</div><p className="mt-1 text-sm text-neutral-500">{invites.isPending ? 'Loading…' : invites.isError ? 'Could not load invitations.' : `${invites.data?.length ?? 0} pending`}</p><Link to={`/app/${workspace.slug}/settings/members`} className="mt-3 inline-block text-sm font-medium underline underline-offset-2">Review invitations</Link></div> : null}</section> : null}
      {section === 'danger' ? <section><h2 className="text-base font-semibold">Danger zone</h2><p className="mt-1 text-sm text-neutral-500">These actions change your access to this workspace.</p><div className="mt-6 divide-y divide-neutral-100 rounded-xl border border-neutral-200"><div className="flex flex-wrap items-center justify-between gap-4 p-5"><div><div className="text-sm font-medium">Leave workspace</div><p className="mt-1 text-xs text-neutral-500">You will lose access to its pages, collections, and teams.</p></div><Button variant="danger" disabled={role === 'OWNER' || devBypassEnabled} onClick={() => setConfirm('leave')}>Leave workspace</Button></div>{role === 'OWNER' ? <div className="flex flex-wrap items-center justify-between gap-4 p-5"><div><div className="text-sm font-medium">Delete workspace</div><p className="mt-1 text-xs text-neutral-500">Permanently removes the workspace and its content.</p></div><Button variant="danger" disabled={devBypassEnabled} onClick={() => setConfirm('delete')}>Delete workspace</Button></div> : null}</div>{role === 'OWNER' ? <p className="mt-3 text-xs text-neutral-500">Owners must transfer ownership before leaving.</p> : null}</section> : null}
    </div>
  </div><Modal open={Boolean(confirm)} onClose={() => { setConfirm(null); setDeleteName('') }} title={confirm === 'delete' ? 'Delete workspace' : 'Leave workspace'}><p className="text-sm text-neutral-600">{confirm === 'delete' ? `This permanently deletes ${workspace.name} and its content. Type its name to confirm.` : `Leave ${workspace.name}? You will lose access immediately.`}</p>{confirm === 'delete' ? <Input autoFocus className="mt-4" value={deleteName} onChange={(event) => setDeleteName(event.target.value)} placeholder={workspace.name} aria-label="Type workspace name to confirm" /> : null}<div className="mt-6 flex justify-end gap-2"><Button onClick={() => setConfirm(null)}>Cancel</Button><Button variant="danger" disabled={danger.isPending || (confirm === 'delete' && deleteName !== workspace.name)} onClick={() => danger.mutate()}>{danger.isPending ? 'Working…' : confirm === 'delete' ? 'Delete workspace' : 'Leave workspace'}</Button></div></Modal></div>
}
